apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: clientapi
  name: clientapi
  namespace: vijay-dev01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clientapi
  template:
    metadata:
      labels:
        app: clientapi
    spec:
      containers:
        - name: clientapi
          image: vijaydev01reg.azurecr.io/clientapi:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: clientapi
  labels:
    app: clientapi
  namespace: vijay-dev01
spec:
  selector:
    app: clientapi
  ports:
    - port: 8090
      targetPort: 8080
      name: http
  type: LoadBalancer

