# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - vijayclientapi

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Java version
      uses: actions/setup-java@v1
      with:
        java-version: '11'
        
    - name: Change wrapper permissions
      run: chmod +x ./gradlew

    - name: Gradle build
      run: ./gradlew clean build

#    - name: Deploy to Azure Web App
#      uses: azure/webapps-deploy@v2
#      with:
#        app-name: 'vijayclientapi'
#        slot-name: 'production'
#        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1a761b8b2d54440e9b282537f7075a10 }}
#        package: '${{ github.workspace }}/build/libs/*.jar'
